import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowsRotate,
  faBed,
  faBolt,
  faCalendarDays,
  faChartColumn,
  faChartLine,
  faChartPie,
  faChevronRight,
  faCircleExclamation,
  faCircleInfo,
  faDumbbell,
  faFire,
  faFireFlameCurved,
  faGaugeHigh,
  faHeart,
  faHeartPulse,
  faLightbulb,
  faList,
  faLungs,
  faMedal,
  faPen,
  faPersonBiking,
  faPersonHiking,
  faPersonRunning,
  faPersonSwimming,
  faPersonWalking,
  faRoad,
  faSpa,
  faStopwatch,
  faTableColumns,
  faTrophy,
  faUser,
  faWandMagicSparkles,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import type { App } from 'vue'

library.add(
  faArrowsRotate,
  faBed,
  faBolt,
  faCalendarDays,
  faChartColumn,
  faChartLine,
  faChartPie,
  faChevronRight,
  faCircleExclamation,
  faCircleInfo,
  faDumbbell,
  faFire,
  faFireFlameCurved,
  faGaugeHigh,
  faHeart,
  faHeartPulse,
  faLightbulb,
  faList,
  faLungs,
  faMedal,
  faPen,
  faPersonBiking,
  faPersonHiking,
  faPersonRunning,
  faPersonSwimming,
  faPersonWalking,
  faRoad,
  faSpa,
  faStopwatch,
  faTableColumns,
  faTrophy,
  faUser,
  faWandMagicSparkles,
  faXmark,
)

export function installFontAwesome(app: App) {
  app.component('FontAwesomeIcon', FontAwesomeIcon)
}
